frame_splitter:
  save_dir: save/keyframes
transform:
  image_size: 224
beit:
  semantic:
    model_path: checkpoints/beit3_large_patch16_224_nlvr2.pth
    tokenizer_path: checkpoints/beit3_semantic.spm
  retrieval:
    model_path: checkpoints/beit3_base_patch16_224_retrieval.pth
    tokenizer_path: checkpoints/beit3_retrieval.spm
captioner:
  model_path: OpenGVLab/InternVL2_5-1B
yolo:
  imgsz: 640  # Kích thước ảnh đầu vào cho YOLOv12
  conf: 0.5   # Ngưỡng confidence

storage:
  features_dir: "save\\features"  # Thư mục lưu vector đặc trưng
  
  